x, y, z = 3, 5, 7

print(x == 3)
print(x < y)
print(x >= y)
print(x <= y)
print(x != y -2)
print(x < 10)
print(x >= 0)
print(x < 0 and x<10)
print(x >= 0 and x <2)
print(x <0 or x <10)
print(x>0 or x<10)
print(x<0 or x>10)
print("\n")
x, y = 3,5
b1, b2, b3, b4 = True, False, x==3, y<3

print(b3)
print(b4)
print(not b1)
print(not b2)
print(not b3)
print(not b4)
print(b1 and b2)
print(b1 or b2)
print(b1 and b3)
print(b1 or b3)
print(b1 and b4)
print(b1 or b4)
print(b2 and b3)
print(b2 or b3)
print(b1 and b2)
print(b1 or b2 and b3)
print(b1 and b2 and b3)
print(b1 or b2 or b3)
print(not b1 and b2 and b3)
print(not b1 or b2 or b3)
print(not(b1 and b2 and b3))
print(not(b1 or b2 or b3))
print(not b1 and not b2 and not b3)
print(not b1 or not b2 or not b3)
print(not(not b1 and not b2 and not b3))
print(not(not b1 or not b2 or not b3))
      
      
